# 打包后会排除该文件
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/seezoon-distributed-id?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&connectTimeout=1000&socketTimeout=60000&rewriteBatchedStatements=true
    username: root
    password:
id:
  server:
    enableAuth: true
    init-get: true
grpc:
  server:
    support-reflection: true
  client:
    common:
      interceptors:
        - com.seezoon.grpc.support.TraceClientInterceptor
    channels:
      distributed-id-service-channel:
        target: 127.0.0.1:9000
    stubs:
      - clazz: com.seezoon.DistributedIdGrpc.DistributedIdBlockingStub
        channel: distributed-id-service-channel
